// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it may be overwritten.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "dummy-api-key",
  authDomain: "dummy-auth-domain",
  projectId: "dummy-project-id",
  storageBucket: "dummy-storage-bucket",
  messagingSenderId: "dummy-messaging-sender-id",
  appId: "dummy-app-id",
};
